import Lynx
import UIKit

// No storyboard: the project is generated by XcodeGen from project.yml, so
// there is no Xcode template to lean on. The window lives in SceneDelegate
// (wired up via UIApplicationSceneManifest in project.yml).
@main
class AppDelegate: UIResponder, UIApplicationDelegate {
    func application(
        _ application: UIApplication,
        didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?
    ) -> Bool {
        // Boots the Lynx runtime. The LynxService pods (Image/Log/Http)
        // self-register once linked; no explicit service wiring needed.
        LynxEnv.sharedInstance()
        return true
    }
}
